AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  SuggestExtensions: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Layout/LineLength:
  Max: 130
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/ClassLength:
  Max: 150
  Exclude:
    - lib/aws/lex/conversation/simulator.rb
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
Metrics/MethodLength:
  Max: 25
Metrics/ModuleLength:
  Exclude:
    - lib/aws/lex/conversation/spec/matchers.rb
Naming/FileName:
  Enabled: true
  Exclude:
    - lib/aws-lex-conversation.rb
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/Documentation:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/GuardClause:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
